conf: variscite: add variscite-mirror for linuxptp
Add mirror for the package linuxptp.

ERROR: linuxptp-1.6-r0 do_fetch: Fetcher failure: Fetch command failed with exit code 8, output:
https://sourceforge.net/projects/linuxptp/files/v1.6/linuxptp-1.6.tgz:
2024-11-28 12:04:55 ERROR 404: Not Found.

ERROR: linuxptp-1.6-r0 do_fetch: Function failed: Fetcher failure for URL: 'http://sourceforge.net/projects/linuxptp/files/v1.6/linuxptp-1.6.tgz'. Unable to fetch URL from any source.

At the time, the TI processor SDK source mirror [1] still provides the tarball
linuxptp-1.6.tgz. Let's move to this mirror to fix the fetch issue.

This will add TI and Variscite source mirror for this package.

[1] https://software-dl.ti.com/processor-sdk-mirror/sources

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>