bmap-tools: update SCR_URI to use main branch
The upstream repository has renamed from master branch to main. This
causes fetch errors like:

ERROR: bmap-tools-native-3.5+gitAUTOINC+db7087b883-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; ... failed with exit code 128, output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
ERROR: bmap-tools-native-3.5+gitAUTOINC+db7087b883-r0 do_fetch: Fetcher failure for URL: 'git://github.com/intel/bmap-tools'. Unable to fetch URL from any source.

Fix it by add a bbappend adding ";branch=main" conditionally.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>