mobile-broadband-provider-info: update SCR_URI to use main branch
The upstream repository has renamed from master branch to main. This
causes fetch errors like:

ERROR: mobile-broadband-provider-info-1_20190618-r0 do_fetch: Fetcher failure: Unable to find revision 22b49d86fb7aded2c195a9d49e5924da696b3228 in branch master even from upstream
ERROR: mobile-broadband-provider-info-1_20190618-r0 do_fetch: Fetcher failure for URL: 'git://gitlab.gnome.org/GNOME/mobile-broadband-provider-info.git;protocol=https'. Unable to fetch URL from any source.

Fix it by add a bbappend adding ";branch=main" conditionally.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>