conf: variscite: add variscite-mirror for libvncserver
Add mirror for the package libvncserver.

ERROR: libvncserver-0.9.10-r0 do_fetch: Fetcher failure: Fetch command failed with exit code 4, no output
ERROR: libvncserver-0.9.10-r0 do_fetch: Function failed: Fetcher failure for URL: 'ftp://ftp.debian.org/debian/pool/main/libv/libvncserver/libvncserver_0.9.10+dfsg.orig.tar.xz'. Unable to fetch URL from any source.

Add Debian mirror snapshot 20150212T040413Z which includes the missing
package libvncserver_0.9.10+dfsg.orig.tar.xz.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>