conf: variscite: add override for connectivity check
Override CONNECTIVITY_CHECK_URIS to fix a broken connectivity check.

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Fetcher failure for URL: 'https://eula-downloads.yoctoproject.org/index.php'. URL https://eula-downloads.yoctoproject.org/index.php doesn't work. Please ensure your network is configured correctly.

Inherit from: https://github.com/nxp-imx/meta-fsl-bsp-release/commit/b83bf77639aa168af815d4a7877d7fd92a8e861c

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>