vkmark: use SHA in SRCREV instead of AUTOREV
Using AUTOREV in SRCREV makes the package fetch and build
the latest commit of a given git branch. It was causing a
version mismatch between vkmark and meson, resulting in:

ERROR: vkmark-1.0-r0 do_configure: meson failed
ERROR: vkmark-1.0-r0 do_configure: Function failed: do_configure
Log data follows:
| DEBUG: Executing shell function do_configure
| The Meson build system
| Version: 0.44.1
| Source dir: build_xwayland/tmp/work/aarch64-poky-linux/vkmark/1.0-r0/git
| Build dir: build_xwayland/tmp/work/aarch64-poky-linux/vkmark/1.0-r0/build
| Build type: cross build
|
| Meson encountered an error in file meson.build, line 1, column 0:
| Meson version is 0.44.1 but project requires >=0.45.

Use a specific SHA to align with NXP's patch.

https://github.com/nxp-imx/meta-fsl-bsp-release/commit/b2446158fc582e6d79b262f252fb3af2e665193f

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>