puzzles: update SCR_URI to use main branch
The upstream repository has renamed from master branch to main. This
causes fetch errors like:

ERROR: puzzles-2_0.0+gitAUTOINC+c6e0161dd4-r0 do_fetch: Fetcher failure: Unable to find revision c6e0161dd475415316ed66dc82794d68e52f0025 in branch master even from upstream
ERROR: puzzles-2_0.0+gitAUTOINC+c6e0161dd4-r0 do_fetch: Fetcher failure for URL: 'git://git.tartarus.org/simon/puzzles.git'. Unable to fetch URL from any source.

Fix it by adding a bbappend to add the branch=main parameter in SRC_URI.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>