Revert "conf: variscite-mirrors: add mirror for branches named master"
This reverts commit 54257935e0c8c21ef22ef4f1137934246f745bdc.

Even though this patch would fix the fetching issue, it still
introduces another error in do_unpack() during bitbake:

error: the requested upstream branch 'origin/master' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>