firmware-imx: fix SRC_URI destsuffix
This fixes the following error introduced by
https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/commit/?h=krogoth_4.1.y&id=82b5aaf55f48e468761c56876ae65fe9af081699

ERROR: firmware-imx-1_5.4-r0 do_install: Function failed: do_install (log file is located at /workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/temp/log.do_install.2614184)
ERROR: Logfile of failure stored in: /workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/temp/log.do_install.2614184
Log data follows:
| DEBUG: Executing shell function do_install
| 'firmware/Android.mk' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/Android.mk'
| 'firmware/epdc' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc'
| 'firmware/epdc/epdc_ED060XH2C1.fw.nonrestricted' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/epdc_ED060XH2C1.fw.nonrestricted'
| 'firmware/epdc/fsl-epdc.mk' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/fsl-epdc.mk'
| 'firmware/epdc/epdc_E60_V110.fw' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/epdc_E60_V110.fw'
| 'firmware/epdc/epdc_E60_V220.fw' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/epdc_E60_V220.fw'
| 'firmware/epdc/epdc_E060SCM.fw' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/epdc_E060SCM.fw'
| 'firmware/epdc/epdc_E97_V110.fw' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/epdc/epdc_E97_V110.fw'
| 'firmware/sdma' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma'
| 'firmware/sdma/sdma-imx31-to2.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx31-to2.bin'
| 'firmware/sdma/sdma-imx51-to3.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx51-to3.bin'
| 'firmware/sdma/sdma-imx35-to1.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx35-to1.bin'
| 'firmware/sdma/sdma-imx31-to1.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx31-to1.bin'
| 'firmware/sdma/sdma-imx35-to2.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx35-to2.bin'
| 'firmware/sdma/sdma-imx53-to1.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx53-to1.bin'
| 'firmware/sdma/sdma-imx25-to1.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/sdma/sdma-imx25-to1.bin'
| 'firmware/vpu' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu'
| 'firmware/vpu/vpu_fw_imx53.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx53.bin'
| 'firmware/vpu/vpu_fw_imx27_TO2.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx27_TO2.bin'
| 'firmware/vpu/vpu_fw_imx27_TO1.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx27_TO1.bin'
| 'firmware/vpu/vpu_fw_imx51.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx51.bin'
| 'firmware/vpu/vpu_fw_imx6q.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx6q.bin'
| 'firmware/vpu/vpu_fw_imx6d.bin' -> '/workdir/build_x11/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/firmware-imx/1_5.4-r0/image/lib/firmware/vpu/vpu_fw_imx6d.bin'
| cp: cannot stat 'git/brcm/1BW_BCM43340/*.bin': No such file or directory

Signed-off-by: Nate Drude <nate.d@variscite.com>